/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generatedocs/wiki/special-activities/_category_.jsons a sidebar from the docs folder structure
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
  

  // But you can create a sidebar manually
  
  // wikiSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: '特色活动',
  //     items: ['special-activities/activity_安装培训','special-activities/activity_开源软件讲座','special-activities/activity_教学实践','special-activities/activity_用户技术交流会'],
  //   },
  //   'LUG_每周聚会'
  // ],
  
};

module.exports = sidebars;
